// Consider classes (after compilation):

class bNode {
	private Object first;

	public bNode(Object first) {
		this.first = first;
	}

	public void setFirst(Object first) {
		this.first = first;
	}
}

class mNode extends bNode {
	public mNode(Integer first) {
		super(first);
	}
	public void setFirst(Integer first) {
		super.setFirst(first);
	}
	
	// after type erasure method signatures do not match
	
	// Bridge method would be generated by compiler
	// 
	public void setFirst(Object first) {
		setFirst((Integer) first);
	}
}

public class BridgeMethods {

}
